# Lectura de fuentes de Datos con Pandas
Para este tema usaremos los archivos de ejemplo en [este folder](https://drive.google.com/drive/folders/1mSVesRg7VNjEmBE8laRQqW9Y7ull3OOX?usp=drive_link).

## Lectura de tablas en archivos planos

**Pandas** es una librería con gran potencial para lectura de datos. A continuación se enumeran algunas de las facilidades que presenta sus funciones de lectura:

* Lidiar con codificaciones extrañas
* Encabezados de tablas
* Columnas
* Parsear columnas de fechas
* Setear tipo de datos
* Encontrar y localizar datos inválidos
* Adjuntar datos a un .csv existente

Las funciones `read_csv()` y `read_table()` de **pandas** se utilizan para leer datos desde archivos, pero tienen algunas diferencias clave:

### Función read_csv
La función `read_csv()` de pandas se utiliza para leer archivos CSV (Comma-Separated Values) y convertirlos en un *DataFrame*.
* Delimitador por defecto: Utiliza una coma (`,`) como delimitador.
* Uso común: Ideal para archivos **CSV** (Comma-Separated Values).
* Parámetros adicionales: Permite especificar el delimitador usando el parámetro `sep`, aunque por defecto ya está configurado para archivos CSV.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

DIR = "/content/drive/MyDrive/Analítica de datos - UF3 /3.2/3.2.1/Datos"
os.chdir(DIR)

In [ ]:
# Comando bash para desplegar el contenido sin abrirlo en un programa externo
!head dates.txt

date,product,price
1/1/2019,A,10
2/1/2020,B,20
3/1/1998,C,30

In [ ]:
import pandas as pd

df = pd.read_csv('dates.txt') # sep: coma
df

       date product  price
0  1/1/2019       A     10
1  2/1/2020       B     20
2  3/1/1998       C     30

`sep`: Delimitador de los campos. Por defecto es una coma (`,`), pero puedes cambiarlo si el archivo usa otro delimitador.

In [ ]:
# !head es un comando bash para desplegar el contenido del documento
!head data.csv

Age|Sex|ID|Race|Country|Education|Education-Num|Marital Status|Relationship
39.0| Male|49084| White| United-States| Bachelors|13.0| Never-married| Not-in-family
50.0| Male|68553| White| United-States| Bachelors|13.0| Married-civ-spouse| Husband
38.0| Male|143654| White| United-States| HS-grad|9.0| Divorced| Not-in-family
53.0| Male|41510| Black| United-States| 11th|7.0| Married-civ-spouse| Husband
28.0| Female|195025| Black| Cuba| Bachelors|13.0| Married-civ-spouse| Wife
37.0| Female|231557| White| United-States| Masters|14.0| Married-civ-spouse| Wife
49.0| Female|393526| Black| Jamaica| 9th|5.0| Married-spouse-absent| Not-in-family
52.0| Male|488425| White| United-States| HS-grad|9.0| Married-civ-spouse| Husband
31.0| Female|7496| White| United-States| Masters|14.0| Never-married| Not-in-family

In [ ]:
df = pd.read_csv('data.csv')
df

      Age|Sex|ID|Race|Country|Education|Education-Num|Marital Status|Relationship
0      39.0| Male|49084| White| United-States| Bachel...
1      50.0| Male|68553| White| United-States| Bachel...
2      38.0| Male|143654| White| United-States| HS-gr...
3      53.0| Male|41510| Black| United-States| 11th|7...
4      28.0| Female|195025| Black| Cuba| Bachelors|13...
...                                                  ...
48838  39.0| Female|735617153| White| United-States| ...
48839  64.0| Male|1131807446| Black| United-States| H...
48840  38.0| Male|781422087| White| United-States| Ba...
48841  44.0| Male|161771296| Asian-Pac-Islander| Unit...
48842  35.0| Male|1344995623| White| United-States| B...

[48843 rows x 1 columns]

In [ ]:
# Corregimos el separador
df = pd.read_csv('data.csv', sep='|')
df.head()

,Age,Sex,ID,Race,Country,Education,Education-Num,Marital Status,Relationship
0,39.0,Male,49084,White,United-States,Bachelors,13.0,Never-married,Not-in-family
1,50.0,Male,68553,White,United-States,Bachelors,13.0,Married-civ-spouse,Husband
2,38.0,Male,143654,White,United-States,HS-grad,9.0,Divorced,Not-in-family
3,53.0,Male,41510,Black,United-States,11th,7.0,Married-civ-spouse,Husband
4,28.0,Female,195025,Black,Cuba,Bachelors,13.0,Married-civ-spouse,Wife

### Función read_table
* Delimitador por defecto: Utiliza una tabulación (`\t`) como delimitador.
* Uso común: Más adecuado para archivos de texto **tabulados**.
* Parámetros adicionales: También permite especificar otros delimitadores mediante el parámetro `sep`.

In [ ]:
# comando bash para desplegar el contenido
!cat test.txt

a b c d message
1 2 3 4 hello
5 6 7 8 world
9 10 11 12 foo

In [ ]:
# 1 sola columna
# el separador es una tabulación
pd.read_table('test.txt')

  a b c d message
0   1 2 3 4 hello
1   5 6 7 8 world
2  9 10 11 12 foo

In [ ]:
# cambiamos el separador por un espacio
pd.read_table('test.txt', sep=' ')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
!cat dates.txt

date,product,price
1/1/2019,A,10
2/1/2020,B,20
3/1/1998,C,30

In [ ]:
pd.read_csv('dates.txt') # sep= ','

       date product  price
0  1/1/2019       A     10
1  2/1/2020       B     20
2  3/1/1998       C     30

In [ ]:
# Leer igual con read_table
df = pd.read_table('dates.txt', sep=',') # sep: coma
df

       date product  price
0  1/1/2019       A     10
1  2/1/2020       B     20
2  3/1/1998       C     30

In [ ]:
pd.read_table('test.txt', sep=' ')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

**header**: Este argumento de `read_csv()` indica la fila que se utilizará como nombres de las columnas. Por defecto es 0 (la primera fila) pero en algunos escenarios puede ser útil cambiar esto. Veámos:

In [ ]:
!cat test.txt

a b c d message
1 2 3 4 hello
5 6 7 8 world
9 10 11 12 foo

In [ ]:
# Caso sin cabecera
pd.read_table('test.txt', sep=' ', header=None)

   0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [ ]:
# Caso con cabecera en 2da fila
pd.read_table('test.txt', sep=' ', header=1)

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

Podemos especificar otras cabecera de columnas con el argumento `names`:

In [ ]:
pd.read_table('test.txt', sep=' ', names=['N1','N2','N3','N4','Mensaje'])

  N1  N2  N3  N4  Mensaje
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

El argumento `parse_dates` en la función `read_csv` de **pandas** se utiliza para especificar qué columnas del archivo CSV deben ser interpretadas como **fechas**. Esto permite que pandas convierta automáticamente esas columnas en objetos de tipo *datetime*, facilitando el análisis de datos temporales.

Nota: `parse_dates` puede usarse con una columna única, varias columnas y columnas combinadas (varias columnas que juntas forman una fecha).

In [ ]:
!cat dates.txt

date,product,price
1/1/2019,A,10
2/1/2020,B,20
3/1/1998,C,30

In [ ]:
df.info() # La columna date se tomó como object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     3 non-null      object
 1   product  3 non-null      object
 2   price    3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
# 1er caso: leer y despues convertir a datetime
df = pd.read_csv('dates.txt')
df.date = pd.to_datetime(df.date, dayfirst=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     3 non-null      datetime64[ns]
 1   product  3 non-null      object
 2   price    3 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 204.0+ bytes

In [ ]:
# 2do caso: convierte a datetime desde la lectura
df = pd.read_csv('dates.txt', parse_dates=['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     3 non-null      datetime64[ns]
 1   product  3 non-null      object
 2   price    3 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 204.0+ bytes

### Parseo manual de fechas

**Columnas combinadas**: Si tienes varias columnas que juntas forman una fecha (por ejemplo, año, mes y día), puedes pasarlas como una lista de listas.

In [ ]:
!cat data_4.csv

year,month,day,product,price
2019,1,1,A,10
2020,1,2,B,20
2021,1,4,C,30
2019,1,5,D,40

In [ ]:
pd.read_csv('data_4.csv')

   year  month  day product  price
0  2019      1    1       A     10
1  2020      1    2       B     20
2  2021      1    4       C     30
3  2019      1    5       D     40

In [ ]:
df=pd.read_csv('data_4.csv',
               parse_dates=[['year', 'month', 'day']])
# orden: year, month, day
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year_month_day  4 non-null      datetime64[ns]
 1   product         4 non-null      object
 2   price           4 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 228.0+ bytes

/tmp/ipython-input-1524923778.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df=pd.read_csv('data_4.csv',

In [ ]:
# Conversión una vez se descontinue parse_dates
df = pd.read_csv('data_4.csv')
df['date']=pd.to_datetime(df[['year', 'month', 'day']])
df.drop(columns=['year', 'month', 'day'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   product  4 non-null      object
 1   price    4 non-null      int64
 2   date     4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 228.0+ bytes

**Parseo indicando formato fecha y hora**

El argumento `date_format` en la función `read_csv` permite especificar una función personalizada para analizar las fechas al leer el archivo CSV. Esto es útil cuando las fechas en el archivo tienen un formato que no es reconocido automáticamente o cuando deseas aplicar una lógica específica al convertir las cadenas de texto en objetos de tipo `datetime`.

* Note: The argument 'date_parser' is deprecated and will be removed in a future version.

In [ ]:
!cat data_6.csv

date,product, price
2016-6-10 20:30:0,A,10
2016-7-1 19:45:30,B,20
2016-10-12 4:5:1,C,30

In [ ]:
pd.read_csv('data_6.csv').info() # lo toma como un object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     3 non-null      object
 1   product  3 non-null      object
 2    price   3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
# indicamos el formato de la fecha
df = pd.read_csv('data_6.csv', parse_dates=['date'],
            date_format='%Y-%m-%d %H:%M:%S')
df

                 date product   price
0 2016-06-10 20:30:00       A      10
1 2016-07-01 19:45:30       B      20
2 2016-10-12 04:05:01       C      30

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     3 non-null      datetime64[ns]
 1   product  3 non-null      object
 2    price   3 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 204.0+ bytes

### Parseo de Booleanos
`read_csv` puede detectar automáticamente booleanos si se le indica.

“asistió” se refiere a la asistencia de un alumno y “Tarea” si completo la tarea o no.

In [ ]:
!head encuesta.txt

                        ID            asistio             Tarea    Comportamiento      Pago
cef3615d61b202f1dc794ef2746df14        1                     1.0              0.0             si
323e5a13644d18185c743c241407754        0                     0.0              NaN             no
b29a107e5cd062e654a63764157461d        0                     0.0              NaN             no
04a11e4bcb573a1261eb0d9948d32637       1                     0.0              0.0             si
9368291c3d5d5f5c8cdb1a575e18bec        1                     0.0              0.0             si
dd0e77eab270e4b67c19b0d6bbf621b        0                     0.0              NaN             no
7599c0aa419b59fd11ffede98a3665d        0                     0.0              NaN             si
6dff182b452487f07a47596f314bddc        0                     1.0              NaN             si
9dc233fed1c6eb2432672ab4bb39249        0                     0.0              NaN             no

In [ ]:
!tail encuesta.txt

8cf2a0f6b368a4a42572f775df0f5f90        1                     1.0              1.0            no
b3d1716309461078c892edcd68db7d4c        1                     0.0              0.0            si
be38b0df499caf723af579aa6b173b0a        0                     1.0              NaN             no
97d2a0572f74acd8c4683ce7b72039db        1                     1.0              0.0            si
4bfe54e669aa8eaf4c9db1b809f3b511        0                     0.0              NaN            no
36f9d95975bfd2c89cfe75baca2d58d2        1                     0.0              0.0            si
e886db962a67fdf6cddbd4e85ea5d6e6        0                     1.0              NaN            si
212332278cfd07d49c4df986e6fbda1e        1                     1.0              0.0            si
fb120d2658407cbedfd9f1136c94ac61        1                     0.0              1.0            si
df891ef669fb23701f6622f14843bda2        0                     1.0              NaN            si

In [ ]:
pd.read_csv('encuesta.txt').head() # no funciona porque solo lee 1 columna

  ID            asistio             Tarea    Comportamiento      Pago
0  cef3615d61b202f1dc794ef2746df14        1      ...
1  323e5a13644d18185c743c241407754        0      ...
2  b29a107e5cd062e654a63764157461d        0      ...
3  04a11e4bcb573a1261eb0d9948d32637       1      ...
4  9368291c3d5d5f5c8cdb1a575e18bec        1      ...

In [ ]:
pd.read_csv('encuesta.txt', sep=' ').head()
# cada espacio en blanco lo interpreta como una nueva columna

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146
0,cef3615d61b202f1dc794ef2746df14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,323e5a13644d18185c743c241407754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b29a107e5cd062e654a63764157461d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04a11e4bcb573a1261eb0d9948d32637,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9368291c3d5d5f5c8cdb1a575e18bec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

`delim_whitespace=True` toma múltiples espacios consecutivos como uno solo

In [ ]:
# index_col: usa X columna como ID
df = pd.read_csv('encuesta.txt', delim_whitespace=True,
                 index_col='ID')
df.head()

/tmp/ipython-input-3631749736.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('encuesta.txt', delim_whitespace=True,

                                  asistio  Tarea  Comportamiento Pago
ID
cef3615d61b202f1dc794ef2746df14         1    1.0             0.0   si
323e5a13644d18185c743c241407754         0    0.0             NaN   no
b29a107e5cd062e654a63764157461d         0    0.0             NaN   no
04a11e4bcb573a1261eb0d9948d32637        1    0.0             0.0   si
9368291c3d5d5f5c8cdb1a575e18bec         1    0.0             0.0   si

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, cef3615d61b202f1dc794ef2746df14 to df891ef669fb23701f6622f14843bda2
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   asistio         30 non-null     int64
 1   Tarea           30 non-null     float64
 2   Comportamiento  18 non-null     float64
 3   Pago            30 non-null     object
dtypes: float64(2), int64(1), object(1)
memory usage: 1.2+ KB

`dtype`: Define el tipo de datos para las columnas especificando con un diccionario.

Ejemplo

`df = pd.read_csv('archivo.csv', dtype={'columna1': 'str', 'columna2': 'int'})`

In [ ]:
df = pd.read_csv('encuesta.txt',
                 delim_whitespace=True,
                 index_col='ID',
                 dtype={'asistio': bool,
                        'Tarea': bool})
df.info() # 'Comportamiento': bool, 'Pago': bool

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, cef3615d61b202f1dc794ef2746df14 to df891ef669fb23701f6622f14843bda2
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   asistio         30 non-null     bool
 1   Tarea           30 non-null     bool
 2   Comportamiento  18 non-null     float64
 3   Pago            30 non-null     object
dtypes: bool(2), float64(1), object(1)
memory usage: 1.8+ KB

/tmp/ipython-input-3496941536.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('encuesta.txt',

In [ ]:
df.sample(3)

                                  asistio  Tarea  Comportamiento Pago
ID
8cf2a0f6b368a4a42572f775df0f5f90     True   True             1.0   no
13b67c51d575bf29827debf0618b445      True  False             0.0   si
e886db962a67fdf6cddbd4e85ea5d6e6    False   True             NaN   si

In [ ]:
df = pd.read_csv('encuesta.txt',
                 delim_whitespace=True,
                 index_col='ID',
                 dtype={'asistio': bool, 'Tarea': bool,
                        #'Comportamiento': bool,
                        #'Pago': bool
                        })
df.info() # 'Comportamiento': bool, 'Pago': bool

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, cef3615d61b202f1dc794ef2746df14 to df891ef669fb23701f6622f14843bda2
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   asistio         30 non-null     bool
 1   Tarea           30 non-null     bool
 2   Comportamiento  18 non-null     float64
 3   Pago            30 non-null     object
dtypes: bool(2), float64(1), object(1)
memory usage: 1.8+ KB

/tmp/ipython-input-3019348392.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('encuesta.txt',

**Hallazgos**:
* `Comportamiento` no se puede convertir a `bool` porque tiene valores `NaN`
* `Pago` no se puede convertir porque no se puede "inferir" de `Object` a `bool`

**Pistas**:
* `true_values`: Lista de cadenas que representan `True`.
* `false_values`: Lista de cadenas que representan `False`.
* `na_filter=True`: Busca y convierte valores `NaN` automáticamente.
* `na_filter=False`: Desactiva la búsqueda de `NaN`

In [ ]:
df = pd.read_csv('encuesta.txt',
                 delim_whitespace=True,
                 index_col='ID',
                 dtype={'asistio': bool, 'Tarea': bool},
                 true_values=['si'], false_values=['no']) #
df.sample(5) # Muestra 5 filas al azar

/tmp/ipython-input-3732839972.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('encuesta.txt',

                                  asistio  Tarea  Comportamiento   Pago
ID
212332278cfd07d49c4df986e6fbda1e     True   True             0.0   True
8cf2a0f6b368a4a42572f775df0f5f90     True   True             1.0  False
7599c0aa419b59fd11ffede98a3665d     False  False             NaN   True
e786f1288887afb309eb913d28ffd6b0     True  False             0.0   True
1ae10dc0d6fed06e8954af5f313cedf1    False  False             NaN   True

`na_filter`: controlar si debe o no filtrar los valores que se consideran `NaN`

In [ ]:
df = pd.read_csv('encuesta.txt',
                 delim_whitespace=True,
                 index_col='ID',
                 dtype={'asistio': bool, 'Tarea': bool},
                 true_values=['si'], false_values=['no'],
                 na_filter=False)
print(df.info())
print(df.sample(5))

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, cef3615d61b202f1dc794ef2746df14 to df891ef669fb23701f6622f14843bda2
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   asistio         30 non-null     bool
 1   Tarea           30 non-null     bool
 2   Comportamiento  30 non-null     object
 3   Pago            30 non-null     bool
dtypes: bool(3), object(1)
memory usage: 1.6+ KB
None
                                  asistio  Tarea Comportamiento   Pago
ID
9dc233fed1c6eb2432672ab4bb39249     False  False            NaN  False
dd0e77eab270e4b67c19b0d6bbf621b     False  False            NaN  False
6dff182b452487f07a47596f314bddc     False   True            NaN   True
fb120d2658407cbedfd9f1136c94ac61     True  False            1.0   True
b29a107e5cd062e654a63764157461d     False  False            NaN  False

/tmp/ipython-input-556206417.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('encuesta.txt',

In [ ]:
# na_filter: controlar si debe o no filtrar los valores que se consideran NaN
df = pd.read_csv('encuesta.txt',
                 delim_whitespace=True,
                 index_col='ID',
                 dtype={'asistio': bool, 'Tarea': bool},
                 true_values=['si','1.0'], false_values=['no','0.0','NaN'],
                 na_filter=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, cef3615d61b202f1dc794ef2746df14 to df891ef669fb23701f6622f14843bda2
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   asistio         30 non-null     bool
 1   Tarea           30 non-null     bool
 2   Comportamiento  30 non-null     bool
 3   Pago            30 non-null     bool
dtypes: bool(4)
memory usage: 1.4+ KB

/tmp/ipython-input-2223945294.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('encuesta.txt',

In [ ]:
df.sample(5)

                                  asistio  Tarea  Comportamiento   Pago
ID
87fcfe4315ee8a3fb554d8bf608cb2ac     True  False           False   True
df891ef669fb23701f6622f14843bda2    False   True           False   True
10c74fd18bddfb3e26c1878a853e7f8      True  False           False   True
dd0e77eab270e4b67c19b0d6bbf621b     False  False           False  False
13b67c51d575bf29827debf0618b445      True  False           False   True

Hay más argumentos a explorar, por ejemplo:

* `index_col`: Especifica qué columna usar como índice del DataFrame.
```
df = pd.read_csv('archivo.csv', index_col=0)
# Usa la primera columna como índice
```

* `usecols`: Permite seleccionar un subconjunto de columnas a leer.
```
df = pd.read_csv('archivo.csv', usecols=['columna1', 'columna2'])
```

* `nrows`: Lee solo un número específico de filas.
```
df = pd.read_csv('archivo.csv', nrows=10)
# Lee solo las primeras 10 filas
```

## Hojas de cálculo
* Consisten en datos almacenados de forma tabular en filas y columnas.
* A diferencia de los archivos planos, pueden tener fórmulas y formato.
* Un solo archivo puede tener diferentes hojas de cálculo.

In [ ]:
!head data.xlsx

PK  �W               _rels/.rels���N�0��{�*�5�@���LH�!4�$n���ă��D��Îq~�b��Ln,�0&K^�UY��&c}����qy/6͢~�8GRoC*r�OJ���Aʤ{t�J
e�
y�e}����0HM�!���ӷ�!���阘���rpb�ͼ�0gt{M#}HL�3_J�Z����PK��4��   �  PK  �W               xl/workbook.xml�Sێ�0}�WD~�\�aEhW�M�v��r�	qq��h���![���>����9gf2�9U�{c�V1��@e:j�/�ބy�ʹ�
�<�6Gz��ok<�% Vҏ�`�W\(�"���`��tv�@ab@r$���e�y!$<��<^�yE�.3�/^h6^ʳ���Pt�
   xl/styles.xml�X]o�0}߯���i����:1�e��T�4��V���ӆ��]c @�NJ�5����=��?b�/�9GT�L�9��\���d�D:Ƿ���F�&"&\
:�-�E��/u��MF�F�A�s�i]|q�2�hN�#YP=�T9��T�S���4��;ם99a�X�a�Kɕ� �������M1��dR�SA��	|�I���<'��_>��!�g�#ɥB*]�q������Ԇ]Ζ�0!9㕅'59#��Ƕ���ƨ�(�bVk?��g����jEM��p����c�w7���hM�����EU����6M���T�ʛ����.��a��+[Ō�R~[�qBxIq}�����DCb���\�,�Dk��M�1�m��*�z���d�d�rcj�!+d�nS�܀)���3.Y'�W���qG�[��i���U(M�zfY�k2�.9KENG��Jj�z����'m ʤbO��L����~�Yd ��i�ֿ�&6hzT�X ��D\��2SL�/dȺn���d .�{�"3�鬓�S��'oW��c��pߩv�|1����켶bbbbbv3=ާʩ�Wj�{�f�Oj��Y��?���|���1~�<W���F��L?�m��m�v�����g T�-������i�^��3�C���0�?��޳l�b\3a[�s�s��{'�����ӑf�l+i�Q�qN��k�A���t�*3|�|@�06fBc�!.�PK�f��  �  PK  �W               xl/worksheets/sheet1.xml��ݒGv���܋��Ϝ �p�! F�m�G�#|�4��i�at����]� i�����'B��.Dpqev/쬪�vf}��������7����}��y�j{���Û���>�������/��?v�p�����݇�o������?�_���������yx�|�����������o�_�u�����o~�����a��O}q�����ۧ���틸m����w�v��'���?�{ss�{�����M>��^?�ӿ���������������_����|1����_����ݛOw�w?<|�����Sӟr�g?��7��������>��n�q��������ߟ���ۯ����ӳ��>�|�owo�\~���������������>>�������~��/���ů��_�}��
eM�L͸�D@,�Y!*c�g�	ik[��&�iz�B��7,4){ͣ��U�LKo-d��.bo7���Dmj���"N`��yOTc[e^���m������%��,�O��f2"�D���t�daH#��^�`R��6�/������Z����n��^�)���ޱ��f�,��wx4'�%��Y�e,�I�w�X�&�ش��t�t0��-�qs
�AYH#���-D>���,>Qv��B����M	U�
����9V�AY`N����4���R��,��3Ѱw���^��b�4>f!�����sq�FZ�@3{��k)K�bg>�,`���M�Ȃ����,����Y��>.�f�j!��,Y���|�Y��������ed����,0']7�,����k1K�cJ����Mj�mU*��YH#�9Y`RRy`#�f�Z̒��cq`�	�v��|3MρYhRv�LJ�,�Xr��PY�Y����su�����ZϲQ�$=�ȹp�blz0)�"Kc��p~�R�r�B�Ħw�Y�&l=6y� ^�����FӃIIz0��i!��,Ƶ��P�M��]:�'ն?��W{`f���@��9�e�I	䤱��`�	�.kIK�>�c����J���4����޶���m�H���Y�Z�R���>0؝#�O�Y�	�4=�������&e��5�Gj~��[|�-dkZ����A_L�#����y���}��I��؛N��.|kQK�sY���Q�ĭ�`�cN��9Pid�<F-d#��QKY�Z
t���ǨlR�5�qd��9Xh��X�ܴ8XifOkYK��n펯r�Z�&��R����KӃ{�h��

In [ ]:
pd.read_excel?

In [ ]:
df = pd.read_excel('data.xlsx', sheet_name='Sheet1') # se cuenta a partir de 0
df.head()

,Age,Sex,ID,Race,Country,Education,Education-Num,Marital Status,Relationship
0,39.0,Male,49084,White,United-States,Bachelors,13.0,Never-married,Not-in-family
1,50.0,Male,68553,White,United-States,Bachelors,13.0,Married-civ-spouse,Husband
2,38.0,Male,143654,White,United-States,HS-grad,9.0,Divorced,Not-in-family
3,53.0,Male,41510,Black,United-States,11th,7.0,Married-civ-spouse,Husband
4,28.0,Female,195025,Black,Cuba,Bachelors,13.0,Married-civ-spouse,Wife

In [ ]:
df = pd.read_excel('data.xlsx', sheet_name=1,
                   usecols='C:G,I')
df.head()

Usar `pd.ExcelFile()` es útil cuando necesitas trabajar con un archivo de Excel que contiene múltiples hojas y deseas acceder a ellas de manera eficiente.

In [ ]:
xls = pd.ExcelFile('data.xlsx') # objeto que referencia a la hoja de cálculo
type(xls)

pandas.io.excel._base.ExcelFile

In [ ]:
xls.sheet_names # consulta hojas del archivo

['Sheet1', 'Sheet1_2']

In [ ]:
sht = xls.parse(sheet_name='Sheet1_2')
sht.head()

,Age,Sex,ID,Race,Country,Education,Education-Num,Marital Status,Relationship
0,39.0,Male,49084,White,United-States,Bachelors,13.0,Never-married,Not-in-family
1,50.0,Male,68553,White,United-States,Bachelors,13.0,Married-civ-spouse,Husband
2,38.0,Male,143654,White,United-States,HS-grad,9.0,Divorced,Not-in-family
3,53.0,Male,41510,Black,United-States,11th,7.0,Married-civ-spouse,Husband
4,28.0,Female,195025,Black,Cuba,Bachelors,13.0,Married-civ-spouse,Wife

## Exportar DFs
* read_csv -> to_csv
* read_table -> to_table
* read_excel -> to_excel

In [ ]:
sht.to_csv('sht.csv')

In [ ]:
sht

,Age,Sex,ID,Race,Country,Education,Education-Num,Marital Status,Relationship
0,39.0,Male,49084,White,United-States,Bachelors,13.0,Never-married,Not-in-family
1,50.0,Male,68553,White,United-States,Bachelors,13.0,Married-civ-spouse,Husband
2,38.0,Male,143654,White,United-States,HS-grad,9.0,Divorced,Not-in-family
3,53.0,Male,41510,Black,United-States,11th,7.0,Married-civ-spouse,Husband
4,28.0,Female,195025,Black,Cuba,Bachelors,13.0,Married-civ-spouse,Wife
...,...,...,...,...,...,...,...,...,...
48838,39.0,Female,735617153,White,United-States,Bachelors,13.0,Divorced,Not-in-family
48839,64.0,Male,1131807446,Black,United-States,HS-grad,9.0,Widowed,Other-relative
48840,38.0,Male,781422087,White,United-States,Bachelors,13.0,Married-civ-spouse,Husband
48841,44.0,Male,161771296,Asian-Pac-Islander,United-States,Bachelors,13.0,Divorced,Own-child
48842,35.0,Male,1344995623,White,United-States,Bachelors,13.0,Married-civ-spouse,Husband

In [ ]:
!head sht.csv

,Age,Sex,ID,Race,Country,Education,Education-Num,Marital Status,Relationship
0,39.0, Male,49084, White, United-States, Bachelors,13.0, Never-married, Not-in-family
1,50.0, Male,68553, White, United-States, Bachelors,13.0, Married-civ-spouse, Husband
2,38.0, Male,143654, White, United-States, HS-grad,9.0, Divorced, Not-in-family
3,53.0, Male,41510, Black, United-States, 11th,7.0, Married-civ-spouse, Husband
4,28.0, Female,195025, Black, Cuba, Bachelors,13.0, Married-civ-spouse, Wife
5,37.0, Female,231557, White, United-States, Masters,14.0, Married-civ-spouse, Wife
6,49.0, Female,393526, Black, Jamaica, 9th,5.0, Married-spouse-absent, Not-in-family
7,52.0, Male,488425, White, United-States, HS-grad,9.0, Married-civ-spouse, Husband
8,31.0, Female,7496, White, United-States, Masters,14.0, Never-married, Not-in-family

In [ ]:
# Como serializar (guardar) a CSV
sht.to_csv('sht.csv', index=False) # Index: False, no incluye el indice
!head sht.csv

Age,Sex,ID,Race,Country,Education,Education-Num,Marital Status,Relationship
39.0, Male,49084, White, United-States, Bachelors,13.0, Never-married, Not-in-family
50.0, Male,68553, White, United-States, Bachelors,13.0, Married-civ-spouse, Husband
38.0, Male,143654, White, United-States, HS-grad,9.0, Divorced, Not-in-family
53.0, Male,41510, Black, United-States, 11th,7.0, Married-civ-spouse, Husband
28.0, Female,195025, Black, Cuba, Bachelors,13.0, Married-civ-spouse, Wife
37.0, Female,231557, White, United-States, Masters,14.0, Married-civ-spouse, Wife
49.0, Female,393526, Black, Jamaica, 9th,5.0, Married-spouse-absent, Not-in-family
52.0, Male,488425, White, United-States, HS-grad,9.0, Married-civ-spouse, Husband
31.0, Female,7496, White, United-States, Masters,14.0, Never-married, Not-in-family

In [ ]:
# Como serializar (guardar) a XLSX (Excel)
sht.to_excel('Otro.xlsx', index=False)
#!head Otro.xlsx

In [ ]:
%%timeit
pd.to_pickle(sht, 'serializado.pkl')

22.3 ms ± 504 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
%%timeit
pd.read_pickle('serializado.pkl')

9.87 ms ± 2.04 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [ ]:
import pandas as pd

¿Como se comparan CSV PKL y XLSX?

In [ ]:
%%timeit
df = pd.read_csv('data.csv', sep='|') # lectura CSV a DF
df# despliega

In [ ]:
%%timeit
df.to_excel('dataexcel.xlsx', index=False) # escritura DF a XLSX

In [ ]:
%%timeit
df.to_pickle('datapkl.pkl') # escritura DF a PKL